### ISSUE TITLE
Players can land on the edge of blocks which doesn't kill them

### ISSUE THREAD

**Issue by Restioson** [NucleoidMC/D-Coudre#3]
What it says on the tin. Might need a mixin to fix this, or add some other checks in the game itself.

**Comment by thecatcore** [comment]
hm, [MC-171969](https://bugs.mojang.com/browse/MC-171969) should have been fixed in 1.16-pre3

**Comment by Restioson** [comment]
Hmm... I know that haykam and March have reproduced it (without accessibility client) on 1.16.1 Dé à Coudre
