### ISSUE TITLE
Spawn players looking towards the edge that they will be jumping from

### ISSUE THREAD

**Issue by jaskarth** [NucleoidMC/D-Coudre#7]
It would be easier to play if the player was teleported looking at the edge that they would be jumping from.

**Comment by thecatcore** [comment]
wait what??? It's supposed to tp them the correct way, I'm supplying the yaw :thinking: .

**Comment by thecatcore** [comment]
I mean that should already be the case :thinking: .

**Comment by thecatcore** [comment]
I don't understand how this can happen because I'm setting the direction of the player when I teleport it to the jumping platform.

**Comment by Restioson** [comment]
Maybe it has been fixed since it was open

**Comment by thecatcore** [comment]
It was already the case before... and I'm almost sure I haven't touch to this part of the code since :flushed:.
I was never able to reproduce it
